# Generated by Django 4.1.6 on 2023-02-13 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baseApp', '0002_alter_todotable_username_delete_userdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todotable',
            name='id',
        ),
        migrations.AddField(
            model_name='todotable',
            name='todo_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todotable',
            name='userName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
