# Generated by Django 4.1.6 on 2023-02-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0003_remove_todotable_id_todotable_todo_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todotable',
            name='todo_id',
        ),
        migrations.AddField(
            model_name='todotable',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
